apiVersion: v1
kind: Service
metadata:
  name: rsshd-service
  labels:
    app: rsshd
spec:
  type: LoadBalancer  # Change to NodePort or ClusterIP as needed
  ports:
  - name: ssh
    port: 22
    targetPort: 22
    protocol: TCP
  - name: tunnels
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: rsshd
